### ISSUE TITLE
Software Manager vs Synaptic Package Manager

### ISSUE THREAD

**Issue by callagg2** [linuxmint/lmde-4-cinnamon-beta#12]
Installing the Multimedia Codecs from the Welcome Screen (Dialogue box), it mentions giving permission/access to Synaptic Packager Manager.

Installing the same Multimedia Codes via System Reports mentions giving permission/access to Software Manager. 

Should they not be consistent?

**Comment by callagg2** [comment]
Installing Updates via the Update Manager says "Authentication is required to run the Synaptic Manager" as opposed to "Authentication is required to run the Update Manager" 

- maybe this is necessary to say Synaptic, I don't know, but it would be better if it said Update Manager (in my opinion as an inexperienced user).

**Comment by clefebvre** [comment]
I know it's a bit silly and it shouldn't make much difference from a user point of view, but since we're asking for a program to get elevated permissions, we need to be precise, and the request is actually technically correct. Some software uses synaptic to perform the job, other uses aptdaemon. Although the codecs are the same package, the backend being elevated in these different use cases is different.

Ideally we should converge everything to the same backend. For now though, this is correct.
