### ISSUE TITLE
Kernel upgrade

### ISSUE THREAD

**Issue by Phil995511** [linuxmint/lmde-4-cinnamon-beta#19]
The Debian fonction `apt -t buster-backports install linux-image-amd64` are not recognized, I must to use `apt install -t buster-backports linux-image-amd64`.

After `apt update && apt install -t buster-backports linux-image-amd64 && apt install -t buster-backports linux-headers-amd64 && apt install -t buster-backports firmware-linux firmware-linux-nonfree && reboot` if I start the mintinstall package manager and I make a search with the indication "linux-image" it crash...

I am not sure in this case that the updates of kernel 5.4 are done automatically by the system by `apt update && apt dist-upgrade`. I believe not, to check please. I had to do it manually by `apt install -t buster-backports linux-image-amd64` on my test instalation of LMDE 4 for upgrade from 5.4.8-1 to 5.4.13-1.

The remove old kernels by mintUpdate manager function does not seem to work properly in this situation with the 5.4.x kernel.

Regards.

**Comment by clefebvre** [comment]
Hi @Phil995511 

Kernel management in mintupdate is specific to Mint and not available in LMDE. The reason behind this is commitment on security updates, we've got commitment on the stable archive for security updates, I'm not sure that's the case necessarily for backports.

There's also a technical issue at play with backports, they're priority 100... that's by design, we're not supposed to use backports to get updates. We're just picking manually from them that's all. As such they're not suitable to automatically get updates from for kernel series (like we do with HWE in Ubuntu/Mint).

**Comment by Phil995511** [comment]
I know that DLME 4 is not Mint 19.x :) thank you, I mainly use on Debian 10 Buster now for several months...

Too bad you don't fix the reported problems, users are somewhat dissatisfied and it damages your reputation.

Regards
